### ISSUE TITLE
Tap gesture area to bring up keyboard is extremely small

### ISSUE THREAD

**Issue by DevonKyleSham** [MGohil/PINView.Maui#2] opened 2023-02-02 13:13 UTC
Hi There, I am running your sample project and have tried on 2 LG devices, one running android 8 and the other android 12. When clicking on the pinView, the keyboard does not show up except when a small region in the middle of the pinView is tapped. When I click on the boxes I get the output "PINView: Box Tapped" but the keyboard does not pop up. I only get the output "PINView: PIN Entry Focused" when tapping on the very small region. Is this a bug or am I doing something incorrect?

**Comment by MGohil** [comment] 2023-07-08 05:24
Hi @DevonKyleSham 

Apology for delayed response. I could not reproduce the issue you are mentioning. However, would you try in the new version I released today? Or try pulling the latest source code and check if the issue is still persist or solved?

Thanks.

**Comment by MGohil** [comment] 2024-06-29 14:52
@DevonKyleSham Closing this issue as since long, I didn't get any response back. Kindly re-open in case you come across this in future. Thanks.

**Closed by MGohil** 2024-06-29 14:52 UTC
